import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StophyError } from "./client.js";
import { channelSchema, channelTool } from "./tools/channel.js";
import { creditsTool } from "./tools/credits.js";
import { kidsSchema, kidsTool } from "./tools/kids.js";
import { musicSchema, musicTool } from "./tools/music.js";
import { playlistSchema, playlistTool } from "./tools/playlist.js";
import { searchSchema, searchTool } from "./tools/search.js";
import { suggestSchema, suggestTool } from "./tools/suggest.js";
import { videoSchema, videoTool } from "./tools/video.js";

type ToolHandler<T> = (args: T) => Promise<{
	content: { type: "text"; text: string }[];
}>;

function wrap<T>(fn: ToolHandler<T>): ToolHandler<T> {
	return async (args) => {
		try {
			return await fn(args);
		} catch (err) {
			const message =
				err instanceof StophyError
					? `Stophy error (${err.code}): ${err.message}`
					: `Unexpected error: ${String(err)}`;
			return {
				content: [{ type: "text", text: message }],
			};
		}
	};
}

const readOnly = { readOnlyHint: true, destructiveHint: false };

export function createServer(): McpServer {
	const server = new McpServer({
		name: "stophy",
		version: "1.0.0",
	});

	server.tool(
		"stophy_search_videos",
		"Search YouTube by keyword with optional filters. Returns items[] discriminated by type: video items have {id, videoUrl, title, author, description, duration, durationSec, viewCount, publishedAt, isLive, thumbnails}; short items have {id, shortUrl, title, viewCount, thumbnails}; channel items have {id, channelUrl, name, handle, subscriberCount, thumbnails}; playlist items have {id, playlistUrl, title, author, videoCount, thumbnails}. Also returns continuationToken for the next page. Best for: discovering videos on a topic, finding recent uploads. Not recommended for: fetching a specific video you already have the URL for. Use stophy_get_video instead.",
		searchSchema,
		readOnly,
		wrap(searchTool)
	);

	server.tool(
		"stophy_get_video",
		'Fetch details, transcript, comments, comment replies, or live chat for a YouTube video. type="details": returns video{id, title, author, description, viewCount, likeCount, durationSec, publishedAt, tags, isLive} and related[]. type="transcript": returns {videoId, language{code, name, isAutoGenerated}, isTranslated, availableTracks, segments[{text, start, duration}], text}; if the requested lang has no native track, a machine translation is returned along with a top-level warning. type="comments": returns {videoId, sortBy, items[{id, text, author, likeCount, replyCount, repliesToken}], continuationToken}. type="replies": pass the repliesToken of a comment as continuationToken to fetch its replies. type="livechat": returns {videoId, status (live|upcoming|replay|chat_disabled|not_live), isLive, concurrentViewers, messages[{id, text, author, authorId, timestampUsec, isOwner, isModerator, isVerified, superChatAmount, superChatCurrency}], continuationToken, pollIntervalMs}. Set chatType="top" for moderated Top chat (default) or "live" for all messages. To follow a live stream, poll again passing the previous continuationToken for only new messages, waiting pollIntervalMs between polls; a null continuationToken means the stream ended. Best for: extracting content from a known video URL. Not recommended for: discovering videos. Use stophy_search_videos instead.',
		videoSchema,
		readOnly,
		wrap(videoTool)
	);

	server.tool(
		"stophy_get_channel",
		"Browse a YouTube channel's content. Returns channel{id, name, handle, subscriberCount, videoCount, isVerified, thumbnails} on every tab. tab options: video, short, live (past live streams), playlist, post or community (community posts), course, about. Video and live tabs return items[{id, videoUrl, title, author, publishedAt, thumbnails}]; community returns items[{id, url, content, publishedTimeText, likeCountText, commentCountText, images, video}]; course returns items[{id, courseUrl, playlistUrl, title, videoCount, thumbnails}]. All content tabs paginate with continuationToken. About returns the full profile. Set query to search within the channel (returns matching videos; tab is ignored).",
		channelSchema,
		readOnly,
		wrap(channelTool)
	);

	server.tool(
		"stophy_get_playlist",
		"Get all videos in a YouTube playlist. Returns the playlist title, author, and every video. Paginate with continuationToken.",
		playlistSchema,
		readOnly,
		wrap(playlistTool)
	);

	server.tool(
		"stophy_get_suggestions",
		"YouTube autocomplete suggestions for a partial query. Returns an array of completions. Useful for topic discovery and query expansion.",
		suggestSchema,
		readOnly,
		wrap(suggestTool)
	);

	server.tool(
		"stophy_music",
		'type="search": search YouTube Music with q and optional searchType (song|video|album|artist|playlist|podcast|episode|profile), returns items[] and continuationToken. type="suggest": autocomplete music queries with q. type="song": fetch rich song metadata from videoUrl. type="lyrics": fetch lyrics from videoUrl. type="album": fetch album metadata and tracks from albumUrl. type="artist": fetch artist profile sections from artistUrl. type="playlist": fetch playlist tracks from playlistUrl and optional continuationToken.',
		musicSchema,
		readOnly,
		wrap(musicTool)
	);

	server.tool(
		"stophy_kids",
		'type="search": search YouTube Kids with q and optional continuationToken, returns Kids-safe video items and continuationToken. type="video": fetch YouTube Kids video metadata and related Kids videos from videoUrl. Best for: child-safe discovery and metadata from the YouTube Kids surface.',
		kidsSchema,
		readOnly,
		wrap(kidsTool)
	);

	server.tool(
		"stophy_get_credits",
		"Check your Stophy credit balance. Free, does not cost a credit. Returns remaining credits.",
		{},
		readOnly,
		wrap(creditsTool)
	);

	return server;
}
