import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StophyError } from "./client.js";
import { channelSchema, channelTool } from "./tools/channel.js";
import { creditsTool } from "./tools/credits.js";
import { playlistSchema, playlistTool } from "./tools/playlist.js";
import { searchSchema, searchTool } from "./tools/search.js";
import { suggestSchema, suggestTool } from "./tools/suggest.js";
import { videoSchema, videoTool } from "./tools/video.js";

type ToolHandler<T> = (args: T) => Promise<{
	content: { type: "text"; text: string }[];
}>;

function wrap<T>(fn: ToolHandler<T>): ToolHandler<T> {
	return async (args) => {
		try {
			return await fn(args);
		} catch (err) {
			const message =
				err instanceof StophyError
					? `Stophy error (${err.code}): ${err.message}`
					: `Unexpected error: ${String(err)}`;
			return {
				content: [{ type: "text", text: message }],
			};
		}
	};
}

const readOnly = { readOnlyHint: true, destructiveHint: false };

export function createServer(): McpServer {
	const server = new McpServer({
		name: "stophy",
		version: "1.0.0",
	});

	server.tool(
		"stophy_search_videos",
		"Search YouTube by keyword with optional filters. Returns items[] where each item has: type, id, videoUrl, title, author, description, duration, durationSec, viewCount, publishedAt, publishedAtText, thumbnails, isLive. Also returns continuationToken for the next page. Best for: discovering videos on a topic, finding recent uploads. Not recommended for: fetching a specific video you already have the URL for. Use stophy_get_video instead.",
		searchSchema,
		readOnly,
		wrap(searchTool)
	);

	server.tool(
		"stophy_get_video",
		"Fetch details, transcript, or comments for a YouTube video. type=\"details\": returns video{id, title, author, description, viewCount, likeCount, durationSec, publishedAt, tags, isLive} and related[]. type=\"transcript\": returns {videoId, language{code, name, isAutoGenerated}, segments[{text, start, duration}], text}. type=\"comments\": returns {videoId, items[{id, text, author, likeCount, replyCount, repliesToken}], continuationToken}. Pass repliesToken as continuationToken with type=\"comments\" to fetch replies. Best for: extracting content from a known video URL. Not recommended for: discovering videos. Use stophy_search_videos instead.",
		videoSchema,
		readOnly,
		wrap(videoTool)
	);

	server.tool(
		"stophy_get_channel",
		"Browse a YouTube channel's content. Returns channel{id, name, handle, subscriberCount, videoCount, isVerified, thumbnails} on every tab. Video/short/playlist tabs also return items[{id, videoUrl, title, author, publishedAt, thumbnails}] and continuationToken. About tab returns the full profile including country, joinedDate, viewCount, and links[]. Best for: auditing a creator's catalog, reading channel videos, reading channel description. Not recommended for: fetching a single known video. Use stophy_get_video instead.",
		channelSchema,
		readOnly,
		wrap(channelTool)
	);

	server.tool(
		"stophy_get_playlist",
		"Get all videos in a YouTube playlist. Returns playlist{id, title, author} and items[{id, videoUrl, title, author, publishedAt, thumbnails}] with continuationToken. Best for: processing curated collections, course playlists, or a channel's uploads playlist.",
		playlistSchema,
		readOnly,
		wrap(playlistTool)
	);

	server.tool(
		"stophy_get_suggestions",
		"Get YouTube autocomplete suggestions for a partial query. Returns {q, hl, gl, suggestions: string[]}. Best for: query expansion, topic discovery, and building search UIs.",
		suggestSchema,
		readOnly,
		wrap(suggestTool)
	);

	server.tool(
		"stophy_get_credits",
		"Check your remaining Stophy API credit balance. Returns {credits: number}. Does not consume a credit. Use before running large batch jobs to confirm you have enough credits.",
		{},
		readOnly,
		wrap(creditsTool)
	);

	return server;
}
